services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data 
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3333:3333
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    links:
      - db

volumes:
  pgdata:

